server:
  port: 8080
  servlet:
    context-path: /neo4j

spring:
  profiles:
    active: dev

  neo4j:
    uri: bolt://host:7687
    authentication:
      username: neo4j
      password: neo4j


knife4j:
  enable: true